### ISSUE TITLE
Letterprovider issues

### ISSUE THREAD

**Issue by dhirtzbruch** [fastbolt/excel-writer#2]
In excel, the first 26 column indices are named alphabetically from A - Z. The following column is then AA, AB, ... - the LetterProvider does not respect that. 

Furthermore, in some places the letter provider is not used, but the implementation is repeated (all appearances of "range(...)".

I think, instead of implementing your own logic for the letter provider, you could use `PhpOffice\PhpSpreadsheet\Cell\Coordinate::stringFromColumnIndex`.

**Comment by StvL97** [comment]
Columns beyond Z should work now. I was not able to remove all occurences of range(), as there seems to be no function in PHPspreadsheet to get specific columns without complete coordinates ('A' instead of 'A1').
