### ISSUE TITLE
Default filename

### ISSUE THREAD

**Issue by dhirtzbruch** [fastbolt/excel-writer#3]
When omitting the target filename in the `ExcelGenerator::generateSpreadsheet` method ([here](https://github.com/fastbolt/excel-writer/blob/66eb730c649a76ea39c17f818403d59867177c57/src/ExcelGenerator.php#L120)), the same filename is used for every generated file, which may lead to filename collisions. 

The method should instead generate some unique randomized filename.

**Comment by StvL97** [comment]
added a timestamp to generic file names
