### ISSUE TITLE
Long material numbers are broken in output file

### ISSUE THREAD

**Issue by dhirtzbruch** [fastbolt/excel-writer#4]
Long material numbers are broken in the generated excel sheet.

Input: 
![image](https://user-images.githubusercontent.com/426308/152112325-4cb4dcd5-3db8-453a-a76f-890f157de8dd.png)

Output:
![image](https://user-images.githubusercontent.com/426308/152112279-89993019-9b9c-4750-b16d-377cec2d3040.png)

**Comment by StvL97** [comment]
Seems to be a problem in excel. Numbers up to 15 digits are fine. It adds a "0" to 16+ digit numbers and turns the rest of the digits to 0. But numbers with 20+ digits seemed to be working for some reason.
Large numbers should be displayed correctly now with the latest commit, but will need to be passed as strings to string columns.
